### ISSUE TITLE
Package.json main file

### ISSUE THREAD

**Issue by HalfdanJ** [googlevr/webvr-ui#4]
@hapticdata should we instead of pointing at the `src/index.js` in package.json point to `buid/webvrui.js`? Seems like many other libraries does that (THREE & polyfill at least), allowing to use `require` in ES5 environment.

**Comment by jbreckmckye** [comment]
This is a problem because the build is transpiled, whereas the index points to various ES6 files. This can be an issue in certain environments.

For example, my project uses Webpack with Uglify, which only handles ES5. When Uglify encounters `src/states`, it gets confused by the trailing comma in the exports objects and duly explodes.

**Comment by jbreckmckye** [comment]
In the meanwhile, you can resolve the issue by using a special import path:

`import * as webvrui from 'webvr-ui/build/webvr-ui.min'`
